#OLA properties
#Mon May 11 19:40:16 CEST 2026
openDialog.lastExtAutload=true
openDialog.lastExtEventName=tiomila2026
openDialog.lastExtPort=8081
openDialog.lastExtProtocol=http
openDialog.lastExtURL=192.168.1.21
openDialog.lastTab=1
